services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:2.6
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_BUCKET=iot_data
      - INFLUXDB_ORG=my_org
    volumes:
      - ./influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:9.5.21
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=grafanaadmin
      - GF_SECURITY_ADMIN_PASSWORD=grafanapass
    volumes:
      - ./grafana:/var/lib/grafana

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./python-service:/app
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=admin123
      - INFLUX_ORG=my_org
      - INFLUX_BUCKET=iot_data

networks:
  default:
    name: iot-network
    driver: bridge
